### PR TITLE
Relax Pandas dependency requirement to allow >v2

### PR DESCRIPTION
**Pull request by NatanMish**

### CODE REVIEW

**Comment by imatiach-msft** [comment]
looks like there were some flake8 errors in the build due to updates to dependencies - I am guessing this needs a separate PR, let me send one out

**Comment by NatanMish** [comment]
Link to issue: https://github.com/interpretml/interpret-community/issues/595

**Comment by imatiach-msft** [comment]
I sent a PR here to fix the flake8 errors:
https://github.com/interpretml/interpret-community/pull/597

**Comment by imatiach-msft** [comment]
I also updated the PR to pin scikit-learn as I see one of the tests started failing with scikit-learn 1.5.0 release

**Comment by imatiach-msft** [comment]
@NatanMish  please rebase this PR against latest main, I've merged PR https://github.com/interpretml/interpret-community/pull/597 to fix the build errors

**Comment by imatiach-msft** [comment]
close re-open to re-run notebook tests

**Review by imatiach-msft — APPROVED** [review]

**Comment by imatiach-msft** [comment]
although the build is green it doesn't look like we are testing against pandas >2.0?

**Comment by imatiach-msft** [comment]
image

**Comment by imatiach-msft** [comment]
seems like something else is still pinning it to older version, strange

**Comment by imatiach-msft** [comment]
@NatanMish maybe for now I will go ahead and merge this.  My suspicion is that the ml-wrappers library that interpret-community depends on is bringing in this pandas<2.0 dependency, so we need to fix it there as well.

**Comment by NatanMish** [comment]
Great thank you, when is the next planned release?

**Comment by imatiach-msft** [comment]
I think we still need to resolve the issue in ml-wrappers first. However, the build seems to be broken there right now as well based on PR https://github.com/microsoft/ml-wrappers/pull/175, which may take some work.

**Comment by imatiach-msft** [comment]
Otherwise we are de facto still pulling and using the pinned version

**Pull request merged**
