### PR TITLE
Fix explanation utils DataMapper docs

### PR DESCRIPTION
**Pull request by gregorybchris**
Signed-off-by: Chris Gregory <chgrego@microsoft.com>

### CODE REVIEW

**Comment by gaugup** [comment]
Looks like _transform_data() is not called from anywhere in this repo. Maybe it should be cleaned up as this is an internal function. @imatiach-msft what do you think?

**Comment by imatiach-msft** [comment]
@gaugup great find, it does look like it's not used anywhere, and since it's a private function I agree that we can just remove it

**Review by imatiach-msft — CHANGES_REQUESTED** [review]
setting as "request changes" to remove the method as @gaugup recommended

**Comment by gaugup** [comment]
@gregorybchris it might be a good idea to look at all the methods in explanation_utils.py and clean up the other internal mehods which aren't used by this package.

**Comment by gaugup** [comment]
Opened feature request https://github.com/interpretml/interpret-community/issues/372

**Pull request closed without merging**
