### PR TITLE
Update to check correct version of RAPIDS

### PR DESCRIPTION
**Pull request by Nanthini10**
Fix typo from https://github.com/interpretml/interpret-community/pull/435

Verified to be running on both 21.06 and 21.08 locally.

### CODE REVIEW

**Review by imatiach-msft — APPROVED** [review]
Approved! Thank you for fixing this!

**Comment by imatiach-msft** [comment]
@Nanthini10 can you please sign the DCO so I can merge?  Thank you!

image

**Comment by imatiach-msft** [comment]
hmm seems it's not working, perhaps because you have multiple commits

**Comment by Nanthini10** [comment]
@imatiach-msft Yeah, the two commands seem to be not working. Is there a workaround for this?

**Comment by imatiach-msft** [comment]
@Nanthini10 I just manually overrode it since you are having technical issues and it seems you already signed off on some of the commits which will get squashed anyway

**Comment by imatiach-msft** [comment]
@Nanthini10 I've merged the PR, thank you for this contribution!

**Pull request merged**
